name: Checkout branch and install Node 18
on: push
jobs:
  prepare:
    runs-on: ubuntu-22.04
    steps:
      - name: Get codes
        uses: actions/checkout@v3
      - name: Install Node@18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install npm dependencies
        run: npm ci
      - name: After install
        run: echo "done"
