name: Deployment workflow
on:
  pull_request:
    types: [ready_for_review,synchronize]
    branches: [main]
    paths-ignore: ['.github/workflows/**']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Get codes
        uses: actions/checkout@v3
      - name: Install Node@18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get codes
        uses: actions/checkout@v3
      - name: Install Node@18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test
  build:
    needs: [lint, test]
    runs-on: ubuntu-22.04
    steps:
      - name: Get codes
        uses: actions/checkout@v3
      - name: Install Node@18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  deploy:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - name: Get codes
        uses: actions/checkout@v3
      - name: Install Node@18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - name: Upload artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
          path: dist
