name: Deployment workflow
on:
  pull_request:
    types: [ready_for_review,synchronize]
    branches: [main]
    paths-ignore: ['.github/workflows/**']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Get codes
        uses: ${{ github.repository }}/.github/actions/prepare.yml
