name: Test deployment
on: [push,workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get codes
        uses: actions/checkout@v3

      - name: Install Node@18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install npm dependencies
        run: npm ci
      - name: Install npm dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Get codes
        uses: actions/checkout@v3

      - name: Install Node@18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install npm dependencies
        run: npm ci
      - name: Install npm dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
  deploy:
    needs: [test, lint]
    runs-on: ubuntu-22.04
    steps:
      - name: Get codes
        uses: actions/checkout@v3

      - name: Install Node@18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install npm dependencies
        run: npm ci
      - name: Build artifacts
        run: npm run build
      - name: Deploy
        run: echo "deploying..."
